"""Removed unique constraint from vin for Service Tickets Model

Revision ID: c6cbc5b57e79
Revises: 1f93b9e8eef1
Create Date: 2025-05-02 12:15:27.878855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cbc5b57e79'
down_revision = '1f93b9e8eef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.drop_index('vin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_tickets', schema=None) as batch_op:
        batch_op.create_index('vin', ['vin'], unique=True)

    # ### end Alembic commands ###
