"""Renamed inventory_id to product_id in inventory_service_tickets

Revision ID: cdc91d0560d5
Revises: c17b36ba6a17
Create Date: 2025-05-20 20:50:00.841249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdc91d0560d5'
down_revision = 'c17b36ba6a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('inventory_service_tickets_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inventory', ['product_id'], ['id'])
        batch_op.drop_column('inventory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_service_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('inventory_service_tickets_ibfk_1', 'inventory', ['inventory_id'], ['id'])
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
