"""Created Inventory and InventoryServiceTicket junction tables that junction with Service Tickets

Revision ID: e97792b71119
Revises: c6cbc5b57e79
Create Date: 2025-05-02 15:58:24.075005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97792b71119'
down_revision = 'c6cbc5b57e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_service_tickets',
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('service_ticket_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['service_ticket_id'], ['service_tickets.id'], ),
    sa.PrimaryKeyConstraint('inventory_id', 'service_ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_service_tickets')
    op.drop_table('inventory')
    # ### end Alembic commands ###
